---
virtualmachines:
  - name: "node01"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
  - name: "node02"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
  - name: "node03"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
